//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsDefinitionReductor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BmsDefinitionReductor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Reuse #WAV definition range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefinitionRangeLabelContent {
            get {
                return ResourceManager.GetString("DefinitionRangeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefinitionReductButtonContent {
            get {
                return ResourceManager.GetString("DefinitionReductButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilesListViewFilenameHeader {
            get {
                return ResourceManager.GetString("FilesListViewFilenameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare same length only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LengthMatchCheckBoxContent {
            get {
                return ResourceManager.GetString("LengthMatchCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load bms file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBmsButtonContent {
            get {
                return ResourceManager.GetString("LoadBmsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bms file|*.bms|All file|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBmsDialogFilter {
            get {
                return ResourceManager.GetString("LoadBmsDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFileNotFound {
            get {
                return ResourceManager.GetString("MessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   r2val range is 0 to 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageR2valOutOfRange {
            get {
                return ResourceManager.GetString("MessageR2valOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #WAV range is 01 to ZZ, and left value &lt; right value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageWavOutOfRange {
            get {
                return ResourceManager.GetString("MessageWavOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correlation coefficient threshold (0-1): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string R2LabelContent {
            get {
                return ResourceManager.GetString("R2LabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusLabelContentComplete {
            get {
                return ResourceManager.GetString("StatusLabelContentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusLabelContentProcessing {
            get {
                return ResourceManager.GetString("StatusLabelContentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please load bms file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusLabelContentWaitFile {
            get {
                return ResourceManager.GetString("StatusLabelContentWaitFile", resourceCulture);
            }
        }
    }
}
